# This is a basic workflow to help you get started with Actions

name: AOP Repos Dispatch listening

on:
  repository_dispatch:
    types: [aop-test-trigger]
  workflow_dispatch:

jobs:
  build: # make sure build/ci work properly
    runs-on: macos-latest
    steps:
       - name: Sample Ts Action
         uses: actions-on-packages/sample-ts-action@0.0.1

